# Exceptions in Python

## Class Hierarchy for build in exceptios in python
```
BaseException
 ‚îú‚îÄ‚îÄ BaseExceptionGroup
 ‚îú‚îÄ‚îÄ GeneratorExit
 ‚îú‚îÄ‚îÄ KeyboardInterrupt
 ‚îú‚îÄ‚îÄ SystemExit
 ‚îî‚îÄ‚îÄ Exception
      ‚îú‚îÄ‚îÄ ArithmeticError
      ‚îÇ    ‚îú‚îÄ‚îÄ FloatingPointError
      ‚îÇ    ‚îú‚îÄ‚îÄ OverflowError
      ‚îÇ    ‚îî‚îÄ‚îÄ ZeroDivisionError
      ‚îú‚îÄ‚îÄ AssertionError
      ‚îú‚îÄ‚îÄ AttributeError
      ‚îú‚îÄ‚îÄ BufferError
      ‚îú‚îÄ‚îÄ EOFError
      ‚îú‚îÄ‚îÄ ExceptionGroup [BaseExceptionGroup]
      ‚îú‚îÄ‚îÄ ImportError
      ‚îÇ    ‚îî‚îÄ‚îÄ ModuleNotFoundError
      ‚îú‚îÄ‚îÄ LookupError
      ‚îÇ    ‚îú‚îÄ‚îÄ IndexError
      ‚îÇ    ‚îî‚îÄ‚îÄ KeyError
      ‚îú‚îÄ‚îÄ MemoryError
      ‚îú‚îÄ‚îÄ NameError
      ‚îÇ    ‚îî‚îÄ‚îÄ UnboundLocalError
      ‚îú‚îÄ‚îÄ OSError
      ‚îÇ    ‚îú‚îÄ‚îÄ BlockingIOError
      ‚îÇ    ‚îú‚îÄ‚îÄ ChildProcessError
      ‚îÇ    ‚îú‚îÄ‚îÄ ConnectionError
      ‚îÇ    ‚îÇ    ‚îú‚îÄ‚îÄ BrokenPipeError
      ‚îÇ    ‚îÇ    ‚îú‚îÄ‚îÄ ConnectionAbortedError
      ‚îÇ    ‚îÇ    ‚îú‚îÄ‚îÄ ConnectionRefusedError
      ‚îÇ    ‚îÇ    ‚îî‚îÄ‚îÄ ConnectionResetError
      ‚îÇ    ‚îú‚îÄ‚îÄ FileExistsError
      ‚îÇ    ‚îú‚îÄ‚îÄ FileNotFoundError
      ‚îÇ    ‚îú‚îÄ‚îÄ InterruptedError
      ‚îÇ    ‚îú‚îÄ‚îÄ IsADirectoryError
      ‚îÇ    ‚îú‚îÄ‚îÄ NotADirectoryError
      ‚îÇ    ‚îú‚îÄ‚îÄ PermissionError
      ‚îÇ    ‚îú‚îÄ‚îÄ ProcessLookupError
      ‚îÇ    ‚îî‚îÄ‚îÄ TimeoutError
      ‚îú‚îÄ‚îÄ ReferenceError
      ‚îú‚îÄ‚îÄ RuntimeError
      ‚îÇ    ‚îú‚îÄ‚îÄ NotImplementedError
      ‚îÇ    ‚îú‚îÄ‚îÄ PythonFinalizationError
      ‚îÇ    ‚îî‚îÄ‚îÄ RecursionError
      ‚îú‚îÄ‚îÄ StopAsyncIteration
      ‚îú‚îÄ‚îÄ StopIteration
      ‚îú‚îÄ‚îÄ SyntaxError
      ‚îÇ    ‚îî‚îÄ‚îÄ IndentationError
      ‚îÇ         ‚îî‚îÄ‚îÄ TabError
      ‚îú‚îÄ‚îÄ SystemError
      ‚îú‚îÄ‚îÄ TypeError
      ‚îú‚îÄ‚îÄ ValueError
      ‚îÇ    ‚îî‚îÄ‚îÄ UnicodeError
      ‚îÇ         ‚îú‚îÄ‚îÄ UnicodeDecodeError
      ‚îÇ         ‚îú‚îÄ‚îÄ UnicodeEncodeError
      ‚îÇ         ‚îî‚îÄ‚îÄ UnicodeTranslateError
      ‚îî‚îÄ‚îÄ Warning
           ‚îú‚îÄ‚îÄ BytesWarning
           ‚îú‚îÄ‚îÄ DeprecationWarning
           ‚îú‚îÄ‚îÄ EncodingWarning
           ‚îú‚îÄ‚îÄ FutureWarning
           ‚îú‚îÄ‚îÄ ImportWarning
           ‚îú‚îÄ‚îÄ PendingDeprecationWarning
           ‚îú‚îÄ‚îÄ ResourceWarning
           ‚îú‚îÄ‚îÄ RuntimeWarning
           ‚îú‚îÄ‚îÄ SyntaxWarning
           ‚îú‚îÄ‚îÄ UnicodeWarning
           ‚îî‚îÄ‚îÄ UserWarning
```

## SyntaxError
```python
1var = 2
1=2
111
```

### TypError
```python
x = 'a'
y = 5
print(x+y)
```

## ValueError
```python
a = int('+')
```
## UnboundLocalError
```python
def unbound_error():
    print(x)  # ‚ùå UnboundLocalError: x referenced before assignment
    x = 10
```

## IndexError
```python
x = [1,2,3]
y = x[10]
```

## KeyError
```python
dic = {'name':'ram', 'age':10}
print(dic['height'])
```

## AttributeError
>Occurs when trying to access invalid attribute of an object
```python
class Human:
    def __init__(self, age, height, name):
        self.age = age
        self.height = height
        self.name = name


h1 = Human(10, 23, "falano")
print(h1.name)
print(h1.width)

```
```python
x = 5
x.upper()
```

## ImportError
```python
from math import nofunc # nofunc = any function that does not exist
```

## ModuleNotFoundError
```
import mathematics # not existing module
```

## FileNotFoundError
```python
with open('nonexistingfile.txt', 'rt') as file:
    print("reading file")
```

## ZeroDivisionError
```python
print(5/0)
```

## RecursionError
```python
def func():
  func()

func()

```

## MemoryError
```python
big_list = [1] * (10**10)  # Allocates a list of 10 billion elements
```
```python
data = []
while True:
    data.append("A" * 10**6)  # Add 1MB of data in each iteration
```

## UnicodeError
```python
b'\x80'.decode("utf-8")  # ‚ùå UnicodeDecodeError
```

## UniCodeEncodeError
```python
'ü§£'.encode('ascii')
```

## Overflow error
```python
import math
x = math.exp(1000)  # ‚ùå OverflowError: math range error
```


## Lookup Error
```python
 b'xa1234'.decode('utf-i')
```







